package com.openclaw.digitalbeings.domain.core;

public enum DomainEventType {
    BEING_CREATED,
    IDENTITY_FACET_ADDED,
    RELATIONSHIP_ADDED,
    HOST_CONTRACT_REGISTERED,
    SESSION_REGISTERED,
    LEASE_STATUS_CHANGED,
    REVIEW_ITEM_CHANGED,
    CANONICAL_PROJECTION_REBUILT,
    OWNER_PROFILE_FACT_RECORDED,
    MANAGED_AGENT_SPEC_CHANGED,
    SNAPSHOT_CREATED,
    BEING_IMPORTED
}
